global:
  imagePullPolicy: "IfNotPresent"
  namespace: "nginx"
  owner: "appTeam"
  version: "0.1"
  stage: "dev"

nginx:
  deploymentName: "nginx-dep"
  containerName: "nginx"
  dockerImageTag: "latest"
  serviceName: "nginx-srv"
  serviceType: "ClusterIP"
  port: "80"
  targetPort: "80"
  replicas: "3"
  appName: "nginx"
  tire: "frontend"
  livenessProbe: true 
  initialDelaySeconds: 60
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1
  readinessProbe: true  
  initialDelaySeconds: 60
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3
  successThreshold: 1

