apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nginx.serviceName }} 
  namespace: {{ .Values.global.namespace }} 
spec:
  type: {{ .Values.nginx.serviceType }} 
  ports:
    - port: {{ .Values.nginx.port }}
      targetPort: {{ .Values.nginx.targetPort }}
  selector:
    appName: {{ .Values.nginx.appName | quote}}
